name: "Publish Central"

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: main
        permissions:
            contents: read
            packages: write
    
        steps:
            - uses: actions/checkout@v4
            
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                server-id: central
                server-username: MAVEN_USERNAME
                server-password: MAVEN_USERTOKEN
                settings-path: ${{github.workspace}}/.github

            - name: Publish to Maven central
              run: mvn -B deploy -Dmaven.test.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml
              env:
                MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                MAVEN_USERTOKEN: ${{ secrets.CENTRAL_PASSWORD }}
                SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
