name: Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Create Key File
      run: echo "$GPG_PRIVATE_KEY" > private.key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        
    - name: Import GPG Key
      run: gpg --import --batch private.key
        
    - name: Build
      run: mvn -B package --file pom.xml

    - name: Sign
      run: mvn -B gpg:sign --file pom.xml --settings settings.xml
      
    - name: Publish to OSS
      run: mvn -B deploy --file pom.xml --settings settings.xml
      env:
         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


