name: Sign

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
  
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        #cache: 'maven'
        check-latest: false
        server-id: ossrh 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_USERTOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Sign
      run: mvn -B verify -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
      env:
         MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
         MAVEN_USERTOKEN: ${{ secrets.OSSRH_JIRA_PASSWORD }}
         GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
