name: "Publish Github"

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
  
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{github.workspace}}/.github # lubocation for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -Dmaven.test.skip=true -P github -s $GITHUB_WORKSPACE/.github/settings.xml
      env:
        GITHUB_TOKEN: ${{github.token}}
        MAVEN_USERNAME: ${{ secrets.GUSERNAME }}
        MAVEN_PASSWORD: ${{ secrets.GTOKEN }}