name: "Publish Central"

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        environment: main
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4
        
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                server-id: central
                server-username: MAVEN_USERNAME
                server-password: MAVEN_USERTOKEN
                settings-path: ${{github.workspace}}/.github
                gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                gpg-passphrase: GPG_PASSPHRASE

            - name: Build with Maven
              run: mvn -B package --file pom.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml

            - name: Publish to Maven central
              run: mvn -B deploy -Dmaven.test.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml
              env:
                MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                gpg-passphrase: GPG_PASSPHRASE

    verify:
        runs-on: ubuntu-latest
        environment: main
        permissions:
            contents: read
            packages: write
    
        steps:
            - uses: actions/checkout@v4
        
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                server-id: central
                server-username: MAVEN_USERNAME
                server-password: MAVEN_USERTOKEN
                settings-path: ${{github.workspace}}/.github
                gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                gpg-passphrase: GPG_PASSPHRASE
        
            - name: Sign
              run: mvn -B verify -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml
              env:
                MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                MAVEN_USERTOKEN: ${{ secrets.CENTRAL_PASSWORD }}
                GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    deploy:
        needs: [build,verify]
        runs-on: ubuntu-latest
        environment: main
        permissions:
            contents: read
            packages: write
    
        steps:
            - uses: actions/checkout@v4
            
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                server-id: central
                server-username: MAVEN_USERNAME
                server-password: MAVEN_USERTOKEN
                settings-path: ${{github.workspace}}/.github
                gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                gpg-passphrase: GPG_PASSPHRASE

            - name: Build with Maven
              run: mvn -B package --file pom.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml

            - name: Publish to Maven central
              run: mvn -B deploy -Dmaven.test.skip=true -P central -s $GITHUB_WORKSPACE/.github/settings.xml
              env:
                MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                gpg-passphrase: GPG_PASSPHRASE