name: Sign

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Install gpg secret key
      run: |
         cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
         gpg --list-secret-keys --keyid-format LONG
    
    - name: Sign
      run: mvn -B verify --file pom.xml
      env:
         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
         MAVEN_GPG_KEYNAME: ${{secrets.GPG_KEY_NAME}}
         MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}


